# Generated by Django 3.1.6 on 2021-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(max_length=15000000000000000000000000000000000000000000),
        ),
    ]
