# Generated by Django 3.1.4 on 2021-01-31 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=250)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher_image', verbose_name='Profile Picture')),
                ('teacher_designation', models.CharField(blank=True, max_length=10000000000000, null=True)),
                ('teacher_details', models.CharField(blank=True, max_length=10000000000000, null=True)),
                ('teacher_comment', models.CharField(blank=True, max_length=10000000000000, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
